First commit

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,42 +1,87 @@
 name: 'build-and-publish-anaconda'
 description: 'Build and Publish conda package'
-author: 'Andrew Prokhorenkov, Maxime Borry, Thomas Arsouze'
+author: 'Thomas Arsouze'
 branding:
   icon: 'package'  
-  color: 'purple'
+  color: 'green'
 inputs:
   conda:
-    description: 'Directory with conda recipe. Default . .'
+    description: "Directory with conda recipe. Default `.` ."
     required: false
     default: '.'
   python:
-    description: 'Python version used for building. Defaults 3.9.'
+    description: 'Python3 minor version used for building. Default `9`.'
     required: false
-    default: '3.9'
+    default: '9'
   token:
     description: 'Anaconda access Token (required)'
     required: true
   channels:
-    description: 'Optional Extra anaconda channels to use. Default conda-forge.'
+    description: 'Optional Extra anaconda channels to use. Coma-separated syntax. Default conda-forge.'
     required: false
     default: 'conda-forge'
-  upload:
-    description: 'Optional Channel to publish the anaconda package. Default conda-forge.'
+  label:
+    description: Label of conda package published. Default `main`.
     required: false
-    default: 'conda-forge'
+    default: main
 runs:
   using: "composite"
   steps:
-    - run: cd ${{ inputs.conda }}
+    - name: Check if meta.yml exists in ${{ inputs.conda }} directory
+      id: check-meta
+      working-directory: ./${{ inputs.conda }}
+      run: |
+        echo "::group::Checking the conda directory if the file meta.yaml exists"
+        if [ ! -f meta.yaml ]; then
+           echo "A meta.yaml file with the compilation instructions of the conda package was not found in ${{ inputs.conda }}."
+           exit 1
+        else
+           echo "A meta.yaml file with the compilation instructions of the conda package was found in ${{ inputs.conda }}."
+        fi
+        echo "::endgroup::"
       shell: bash
-    - run: |
-        channels=${{ inputs.channels }}
-        IFS=', ' read -r -a arr_channels<<<"${channels:1:-1}"
-        channels="" 
-        for c in "${arr_channels[@]}"; do channels+="-c $c "; done
-        conda build ${channels} --python=${{ inputs.python }} --output-folder . .
-      shell: bash
-    - run: | 
+    - name: Setup Conda environment
+      uses: conda-incubator/setup-miniconda@v2
+      with:
+        python-version: 3.${{ inputs.python }}
+        channels: ${{ inputs.channels }}
+        auto-update-conda: False
+    - run: conda install conda-build anaconda-client
+      shell: bash -l {0}
+    - name: Package compilation
+      id: package-compilation
+      working-directory: ./${{ inputs.conda }}
+      run: | 
+        echo "::group::Conda packages building"
+        echo "Associate numpy version to python version provided"
+        PYTHON_VERSION="3.${{ inputs.python }}"
+        if [ ${PYTHON_VERSION="3.7"} ]; then
+          NUMPY_VERSION="1.11"
+        elif [ ${PYTHON_VERSION="3.8"} ]; then
+          NUMPY_VERSION="1.16"
+        elif [ ${PYTHON_VERSION="3.9"} ]; then
+          NUMPY_VERSION="1.19"
+        else
+          echo "Unable to build the package with this version of python (yet). Please choose a subversion of Python3: 7, 8 or 9"
+          exit 1
+        fi
+        out_dir=`mktemp -d conda-build-dir.XXXXXX`
+        echo "Running 'conda build' with python ${PYTHON_VERSION} and numpy ${NUMPY_VERSION}"  
+        conda build . --output-folder $out_dir --python=${PYTHON_VERSION} --numpy=${NUMPY_VERSION}
+        echo "::set-output name=out_dir::'$out_dir'"
+        echo "::endgroup::"        
+      shell: bash -l {0}
+    - name: Package uploading
+      id: package-uploading
+      working-directory: ./${{ inputs.conda }}
+      run: | 
+        echo "::group::Conda packages uploading"
         export ANACONDA_API_TOKEN=${{ inputs.token }}
-        anaconda upload --skip-existing --no-progress -u ${{ inputs.upload }}      
-      shell: bash 
+        for BUILD_FILE in ${{ steps.package-compilation.outputs.out_dir }}/*; do
+          if [ "${BUILD_FILE: -8}" == ".tar.bz2" ]; then
+            echo "Upload package ${BUILD_FILE} to anaconda with label $label on channel associated to the given token."
+            anaconda upload --skip-existing --no-progress --label $label ${BUILD_FILE}
+          fi
+        done
+        echo "::endgroup::"   
+      shell: bash -l {0}
